export const products = [
	{
		productName: "Product A",
		productImage: "https://picsum.photos/200/300?random=1",
		productPrice: 19.99,
		productDescription: "Description for Product A",
		isFeatured: true,
	},
	{
		productName: "Product B",
		productImage: "https://picsum.photos/200/300?random=2",
		productPrice: 24.99,
		productDescription: "Description for Product B",
		isFeatured: true,
	},
	{
		productName: "Product C",
		productImage: "https://picsum.photos/200/300?random=3",
		productPrice: 14.99,
		productDescription: "Description for Product C",
		isFeatured: false,
	},
	{
		productName: "Product D",
		productImage: "https://picsum.photos/200/300?random=4",
		productPrice: 29.99,
		productDescription: "Description for Product D",
		isFeatured: true,
	},
	{
		productName: "Product E",
		productImage: "https://picsum.photos/200/300?random=5",
		productPrice: 34.99,
		productDescription: "Premium quality Product E for everyday use.",
		isFeatured: false,
	},
	{
		productName: "Product F",
		productImage: "https://picsum.photos/200/300?random=6",
		productPrice: 39.99,
		productDescription: "Stylish and modern Product F.",
		isFeatured: true,
	},
	{
		productName: "Product G",
		productImage: "https://picsum.photos/200/300?random=7",
		productPrice: 22.49,
		productDescription: "Compact and efficient Product G.",
		isFeatured: false,
	},
	{
		productName: "Product H",
		productImage: "https://picsum.photos/200/300?random=8",
		productPrice: 49.99,
		productDescription: "Durable and high-performance Product H.",
		isFeatured: true,
	},
	{
		productName: "Product I",
		productImage: "https://picsum.photos/200/300?random=9",
		productPrice: 18.99,
		productDescription: "Affordable and lightweight Product I.",
		isFeatured: false,
	},
	{
		productName: "Product J",
		productImage: "https://picsum.photos/200/300?random=10",
		productPrice: 44.99,
		productDescription: "Elegant and reliable Product J.",
		isFeatured: true,
	},
	{
		productName: "Product K",
		productImage: "https://picsum.photos/200/300?random=11",
		productPrice: 15.49,
		productDescription: "Compact and reliable Product K for daily use.",
		isFeatured: false,
	},
	{
		productName: "Product L",
		productImage: "https://picsum.photos/200/300?random=12",
		productPrice: 33.99,
		productDescription: "Advanced features and elegant design.",
		isFeatured: true,
	},
	{
		productName: "Product M",
		productImage: "https://picsum.photos/200/300?random=13",
		productPrice: 19.89,
		productDescription: "Compact yet powerful Product M.",
		isFeatured: false,
	},
	{
		productName: "Product N",
		productImage: "https://picsum.photos/200/300?random=14",
		productPrice: 26.99,
		productDescription: "Lightweight and trendy Product N.",
		isFeatured: true,
	},
	{
		productName: "Product O",
		productImage: "https://picsum.photos/200/300?random=15",
		productPrice: 17.89,
		productDescription: "Perfect choice for quick tasks, Product O.",
		isFeatured: false,
	},
];
